name: localizations
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shimmer_animation: ^2.2.2
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
  generate: true

# 👇 এটা flutter সেকশনের বাইরে রাখতে হবে
flutter_intl:
  enabled: true
